require 'mathematics'

File.open('trignometry.html', 'w') do |file|
  file.write("<html>")
  file.write("  <head>")
  file.write("    <title>")
  file.write("      Trignometry - Ruby Math Module vs Ruby Mathematics Module")
  file.write("    </title>")
  file.write("  </head>")
  file.write("<body bgcolor='lightblue'>")
  file.write("<center>")
  file.write("<h3>Trignometry - Ruby Math Module vs Ruby Mathematics Module</h3>")
  file.write("  <table bgcolor='yellow' cellspacing='5' cellpadding='5' border='5'>")
  file.write("    <tr><th>Trignometric Function</th><th>Using Math Module</th><th>Using Mathematics Module</th>")
  file.write("    <tr><th>sin</th><td>#{Math.sin(0)}</td><td>#{Mathematics.sin(0)}</td>")
  file.write("    <tr><td></td><td>#{Math.sin(0.25*Math::PI)}</td><td>#{Mathematics.sin(0.25*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.sin(0.5*Math::PI)}</td><td>#{Mathematics.sin(0.5*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.sin(0.75*Math::PI)}</td><td>#{Mathematics.sin(0.75*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.sin(Math::PI)}</td><td>#{Mathematics.sin(Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.sin(1.25*Math::PI)}</td><td>#{Mathematics.sin(1.25*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.sin(1.5*Math::PI)}</td><td>#{Mathematics.sin(1.5*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.sin(1.75*Math::PI)}</td><td>#{Mathematics.sin(1.75*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.sin(2*Math::PI)}</td><td>#{Mathematics.sin(2*Math::PI)}</td></tr>")
  file.write("    <tr><th>cos</th><td>#{Math.cos(0)}</td><td>#{Mathematics.cos(0)}</td>")
  file.write("    <tr><td></td><td>#{Math.cos(0.25*Math::PI)}</td><td>#{Mathematics.cos(0.25*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.cos(0.5*Math::PI)}</td><td>#{Mathematics.cos(0.5*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.cos(0.75*Math::PI)}</td><td>#{Mathematics.cos(0.75*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.cos(Math::PI)}</td><td>#{Mathematics.cos(Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.cos(1.25*Math::PI)}</td><td>#{Mathematics.cos(1.25*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.cos(1.5*Math::PI)}</td><td>#{Mathematics.cos(1.5*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.cos(1.75*Math::PI)}</td><td>#{Mathematics.cos(1.75*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.cos(2*Math::PI)}</td><td>#{Mathematics.cos(2*Math::PI)}</td></tr>")
  file.write("    <tr><th>tan</th><td>#{Math.tan(0)}</td><td>#{Mathematics.tan(0)}</td>")
  file.write("    <tr><td></td><td>#{Math.tan(0.25*Math::PI)}</td><td>#{Mathematics.tan(0.25*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.tan(0.5*Math::PI)}</td><td>#{Mathematics.tan(0.5*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.tan(0.75*Math::PI)}</td><td>#{Mathematics.tan(0.75*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.tan(Math::PI)}</td><td>#{Mathematics.tan(Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.tan(1.25*Math::PI)}</td><td>#{Mathematics.tan(1.25*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td style='color:red'>#{Math.tan(1.5*Math::PI)}</td><td>#{Mathematics.tan(1.5*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.tan(1.75*Math::PI)}</td><td>#{Mathematics.tan(1.75*Math::PI)}</td></tr>")
  file.write("    <tr><td></td><td>#{Math.tan(2*Math::PI)}</td><td>#{Mathematics.tan(2*Math::PI)}</td></tr>")
  file.write("  </table>")
  file.write("</center>")
  file.write("</body>")
  file.write("</html>")
end
